version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout

      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy: 
    executor: heroku/default
    steps: 
      - checkout
      - run:
          name: Deploy master to heroku
          command: git push https://heroku:$api_key@git.heroku.com/vite-react-circleci.git

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_test
      - deploy: # Use the pre-configured job, deploy-via-git
          requires:
            - build_and_test