version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
parameters: 
  # api-key: 
  #   default: $api_key
  #   description: The name of the environment variable containing your Heroku API Key.
  #   type: env_var_name
  app-name:
    default: vite-react-circleci
    description: >-
      Add the name of your application to an environment variable with this
      name.
    type: string
  # branch:
  #   default: Master
  #   description: >-
  #     Deploy the given branch. The default value is your current branch. Accepts
  #     strings which may contain an environment variable.
  #   type: string
  # force:
  #   default: false
  #   description: >-
  #     Whether or not to force the git push (i.e. `git push -f`). Defaults to
  #     false.
  #   type: boolean
jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout

      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy: 
    executor: heroku/default
    steps: 
      - checkout
      - run:
          name: Deploy <<parameters.branch>> to heroku
          command: git push https://heroku:$api_key@git.heroku.com/vite-react-circleci.git

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_test
      - deploy: # Use the pre-configured job, deploy-via-git
          requires:
            - build_and_test